---
apiVersion: v1
kind: Service
metadata:
  name: self-signed-certificate-front
spec:
  selector:
    app: self-signed-certificate-front
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-signed-certificate-front-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: self-signed-certificate-front
  template:
    metadata:
      labels:
        app: self-signed-certificate-front
    spec:
      containers:
        - name: self-signed-certificate-front-con
          image: legendzzzaioi/self-signed-certificate-front:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "800m"
              memory: "1000Mi"
